services:
  telemetry_ingestor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: telemetry_ingestor
    container_name: "${COMPOSE_PROJECT_NAME}-ingestor"
    restart: unless-stopped
    volumes:
      - sockets:/opt:rw
    environment:
      TELEMETRY_DB_HOST: timescaledb
    healthcheck:
      test: [ "CMD-SHELL", "grep -q RUNNING /opt/app/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  telemetry_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: telemetry_api
    container_name: "${COMPOSE_PROJECT_NAME}-api"
    restart: unless-stopped
    ports:
      - 5005
    volumes:
      - sockets:/opt:ro
    healthcheck:
      test: [ "CMD-SHELL", "grep -q RUNNING /opt/app/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sockets:
